.rubocop.yml
deploy/action.yml
deploy/lib/deployer.rb
deploy/lib/deployer/config.rb
deploy/lib/deployer/repo.rb
deploy/lib/deployer/repo/base_updater.rb
deploy/lib/deployer/repo/merge_updater.rb
deploy/lib/deployer/repo/pull_request_updater.rb
deploy/run.rb
deploy/spec/deployer/config_spec.rb
deploy/spec/deployer_spec.rb

For prereleases, we want to be able to push updates to either `staging` (for rc's) or a protonova build (for qa releases).  We don't want to go through the hassle of PR's for those, so this PR opens the interface of the action to allow it specify a `change-method` and `branch-name`.  If `change-method` is set to `merge`, then the changes will be merged directly into the branch that is set by `branch-name`.
An example usage might look like this:
```yml
name: Publish
jobs:
publish-to-npm: ...
auto-deploy-prerelease:
needs: publish-to-npm
runs-on: ubuntu-latest
steps:
- name: Build branch name (staging if rc, use PR number and library name if qa) 
run: |
tag_name=${{ github.event.release.tag_name }}
if [[ $VERSION =~ -rc\. ]]; then
echo "branch_name=staging" >> $GITHUB_ENV
else
[[ $tag_name …
```

feat(deploy): add support for merge auto-deploys

---

yarn.lock

we still use v5 for another dependency, but that is not vulnerable.

bump undici to 6.19.8

---

.github/workflows/qa-release.yml
README.md

We want to be able to trigger a complete QA release that does everything in a simple way for our libraries. This shared action:
- creates a QA release
- publishes it
- deploys a protonova environment for all consuming apps.

feat(QA): add combined workflow for deploying QA releases

---

.github/workflows/qa-release.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml
deploy/README.md
deploy/action.yml

In order to fine grain tune our permissions, we want to use a Github app (`Planning Center Dependencies`) to authenticate our updates. This requires us to change the authentication logic.
Also, we no longer need to send in the github token as an argument so that input is removed.

chore: use github app instead of picobot token

---

deploy/README.md
deploy/lib/deployer/repo/base_updater.rb
deploy/spec/deployer/repo/base_updater_spec.rb

The `upgrade-commands` setting for deploys was a bit awkward.  It required each library to configure and know about the special upgrade needs of each library.  In addition, adding new specific settings (like enabling changelog updates) would be difficult.
This new feature reads a `.pco-release.config.yml` file at the root of consumer repos when deploying.  If there is a file, it will read it and use its configuration to override some settings.
Currently, this allows for specifying the `upgrade_command`, which it also uses string replacement to allow for specifying the version and package name.
For instance, tapestry-react will add the file like this:
```yml
upgrade_command: "yarn tr upgrade {{package_name}}@{{version}}"
```
In the future, I hope to also use the config for changelog update …

feat(deploy): allow for reading config for deployment from consumer repos

---

.github/workflows/qa-release.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml
deploy/action.yml
deploy/lib/deployer.rb
deploy/lib/deployer/config.rb
deploy/lib/deployer/repo/base_updater.rb
deploy/lib/deployer/repo/merge_updater.rb
deploy/lib/deployer/repo/pull_request_updater.rb
deploy/lib/deployer/repo/version_compare.rb
deploy/run.rb

We want to take a more manual approach to major version upgrades. This means that we want to check if we are attempting to do a major upgrade
and if so, abort the change.
This was important to do at a per consumer level so that apps that were behind for 1 reason or another would not be accidentally upgraded on a patch release shortly after a major release.

feat(deploy): prevent major versions from deploy

---

.github/workflows/release.yml
deploy/action.yml
deploy/lib/deployer.rb
deploy/lib/deployer/errors.rb
deploy/lib/deployer/repo.rb
deploy/lib/deployer/repo/base_updater.rb
deploy/lib/deployer/repo/merge_updater.rb
deploy/lib/deployer/repo/pull_request_updater.rb
deploy/lib/deployer/reporter.rb
deploy/run.rb
deploy/spec/deployer/repo_spec.rb
deploy/spec/deployer/reporter_spec.rb
deploy/spec/deployer_spec.rb

Because we're not organizationally at a place where we are ready to auto-deploy without any checks, we need to make sure that there is clear communication about the "next steps" after a release is created.  In addition, we want to add clear communication about successes and points of failure.
This PR overhauls the reporting system, bringing it more out of github actions and into a report that shows up on the PR after it is complete.
Here is an example from one of my tests: https://github.com/planningcenter/test-js-auto-deploy-pkg/pull/5
It shows:
- The successful PRs that are created
- Any PRs that failed to create (and what repo they were in)
- A copyable command line command to approve all the PRs created (this is a great way to track who triggered the update so that they can be a point …

feat(release): add more robust reporting 

---

deploy/lib/deployer/config.rb
deploy/lib/deployer/repo/dependabot_pull_request_updater.rb

There was an error in the credentials causing errors occasionally due to credentials being a primitive.  Wrapping them in the dependabot credentials fixes the issue.

fix(deploy): fix the way creds are sent to dependabot

---

.github/workflows/release-candidate.yml
rc-reporting/action.yml

Currently, when an `rc` build is triggered, it is unclear the results of how it goes out to all the apps.  This adds a report to the PR that triggered the rc release that looks like this:
---
- https://app.asana.com/0/0/1208313553826159

feat(rc): add better reporting

---

.github/workflows/qa-release.yml
create-qa-release/action.yml
qa-reporting/action.yml

This improves the reporting to follow a similar reporting structure as #19 . After a qa release is processed, it creates a comment on the PR that triggered it with the following information:
- list of successful repos that it deployed to
- list of repos that it failed to deploy to (and the error message)
- A link to the protonova environment that was triggered
- A tag of the person who triggered the qa release

feat(qa): improve reporting

---

.github/workflows/publish.yml

There was a bug that was happening when building multiple qa releases when `main` remained the same.  The reason for this is that the cache key was based around the `github.sha`.  This is fine when it is triggered by a normal sha, but comments triggering a run actually are run from the `sha` of `main`.  This means that the build directory is cached for ANY qa build going into `main` and it will restore from that point until `main` is a new sha.  An [example of this occurred in add-ons](https://github.com/planningcenter/add-ons-js/actions/runs/10964128584/job/30447122150#step:7:8).
To fix this, we are detecting the actual sha that we're using from the release that we built.

fix: determine actual sha for cache key

---

deploy/lib/deployer/repo/dependabot_pull_request_updater.rb

After making adjustments for apps that use a vendored version of yarn 3, there was a bug that popped up because the return of the `fetcher` was no longer the fetcher.
In order to fix this, I just ensured that we returned the fetcher after sanitizing the yarnrc.
Fixes #24

fix: ensure file fetcher successfully returns

---

sync-with-labels/action.yml

We'd like to use the `sync-with-labels` action in [@planningcenter/add-ons-cli](https://github.com/planningcenter/add-ons-cli), but that package uses `npm`, and the action currently hardcodes `yarn`.

feat(sync-with-labels): make cache configurable

---

deploy/action.yml

Because corepack has a confirmation for downloading the yarn version, it was causing failures.  This skips that confirmation and allows the yarn version to download automatically.

fix: disable yarn version download prompt

---

deploy/lib/deployer/errors.rb
deploy/lib/deployer/repo/dependabot_pull_request_updater.rb

There were scenarios where an upgrade was not compatible because of peerDependencies not being valid.  This caused the version to be upgraded to a lower version than what we intended.  Instead of allowing that to happen, we will now raise an error that communicates why we were not able to upgrade to the newer version.
Fixes #26

feat: raise errors when versions are not supported

---

deploy/action.yml
deploy/lib/deployer.rb
deploy/lib/deployer/config.rb
deploy/lib/deployer/repo.rb
deploy/lib/deployer/repo/base_updater.rb
deploy/lib/deployer/reporter.rb
deploy/lib/deployer/repos.rb
deploy/run.rb
deploy/spec/deployer/config_spec.rb
deploy/spec/deployer/repo/base_updater_spec.rb
deploy/spec/deployer/repo_spec.rb
deploy/spec/deployer_spec.rb

The deploy package currently only deploys one package at a time.  We are moving to a world where monorepos can deploy to multiple packages and we need the deploy action to allow for this behavior.
The big change is that deploy depends on package_names instead of package_name.  If you send in package_name, it will set package_names as `[package_name]`.  Other than that, the only other changes are some minor changes to wording to accommodate multiple packages.

feat: open `deploy` to take package-names

---

.github/workflows/lerna-deploy-rc.yml

In the lerna workflow, when you have a RC that has been created for release PR, you can run `@pco-release deploy` and this will push the release to staging for all products that are associated.
This has been separated from the `@pco-release rc` command for non-lerna builds because rc's are now generated when there is new changes on main.

feat: add lerna-deploy-rc workflow

---

.github/workflows/lerna-qa-release.yml

This new action allows you to add a comment `@pco-release qa` on a PR in a lerna repo.  When doing so, it will create a QA release, publish it, and deploy it to protonova.  If you use `@pco-release qa --no-deploy` it will skip the deploy step.
After working, it will report the QA version to the PR that triggered the creation.

feat: add lerna qa release workflow

---

.github/workflows/lerna-release-on-merge.yml

When a PR is merged in a lerna monorepo, this action will:
- create a release
- publish the release to github and npm
- create PRs in all consuming apps to upgrade to the latest version
- report the results back to the release PR

feat: add lerna-release-on-merge workflow

---

.github/workflows/lerna-release-pr.yml

This adds the `lerna-release-pr` workflow which does the following when changes get merged to `main`:
- creates a new RC build and publishes it (for relevant packages.  This will skip if no changes impact the packages)
- creates or updates the release PR with the correct version bump based on commit history.
- reports back to the release PR about the new RC build (if applicable).

feat: add lerna-release-pr workflow

---

deploy/run.rb

empty strings evaluate to true, so this was falsely using empty strings for package names
---
- https://app.asana.com/0/0/1209131249629386

fix(deploy): properly detect when pkg names is ""

---

.github/workflows/lerna-deploy-rc.yml
.github/workflows/lerna-qa-release.yml
.github/workflows/qa-release.yml
.github/workflows/release-candidate.yml

When a person adds a command like `@pco-release rc`, it can be unclear if anything is happening.  This adds a small feature to add a thumbs up reaction to all commands that trigger.
Closes Issue #42
---
- https://app.asana.com/0/0/1209161257295731

feat: add reactions to comment commands

---

.github/workflows/lerna-qa-release.yml

Prior to this PR, the QA building process for lerna was broken.  The first problem was that it was using the `main` branch to make the builds.  This PR changes that so that the branch of each PR is used.
In order to make that work, more logic was needed to detect specific things about how to build correctly:
- It needs to detect the previous QA version for this PR.  We want to increment (or not build if there are no changes) for each QA  build for this PR.
- It needs to create a better system for detecting changes.  Lerna creates a commit for the version publish, so we need to be able to compare the second to last commit to the current commit of the PR so that we can determine if a new QA build is necessary.
With this done, the QA command will now efficiently create new QA builds in an …

fix(lerna-qa): Fix building QA build

---

reporting/action.yml

Protonova links were not being logged because the environment variable wasn't set up correctly.  This fixes that and ensures that the proto environment is logged to the PR comment.
---
- https://app.asana.com/0/0/1209206999143815

fix(reporting): add proto_tag to env variables

---

deploy/lib/deployer/repo/dependabot_proxy.rb
deploy/lib/deployer/repo/dependabot_pull_request_updater.rb

With the detection whether dependencies exist moving earlier in the process, we were missing the setup of the repo to properly detect if the dependency exists.  Dependabot depends on an environment where npm modules can be referenced and it needs to run `npm install` before running the comparison.
This hoists that behavior to run before any checks are run.  It also detects if it has already been run so that the run isn't repeated unnecessarily.

fix: setup runner in dependabot proxy

---

.github/workflows/lerna-qa-release.yml

we should always run if we don't have a last version

fix: don't skip should_run check if no last version

---

deploy/lib/deployer/repo.rb
deploy/lib/deployer/repo/dependabot_proxy.rb

During the process of checking if a repo has a dependency on the library we're updating, it can check many different types of repos.  Some of those don't have `main` branches or they don't have `package.json` files.   In those cases, we will just rescue from those situations and just say that there are no dependencies.
In addition, I added some logging to give a bit more clarity into when things might be failing.

fix: Don't fail when checking non-compliant repos

---

.github/workflows/lerna-deploy-rc.yml
.github/workflows/lerna-qa-release.yml
.github/workflows/lerna-release-on-merge.yml
.github/workflows/lerna-release-pr.yml
node-cache/action.yml

I had been noticing that many of the builds were taking a lot of time to resolve the node_modules from the `yarn install` command.
This adds some caching around that process so that we can reduce the time it takes to run these commands.

feat(lerna): add caching for node_modules

---

.github/workflows/lerna-deploy-rc.yml
.github/workflows/release-candidate.yml

Because major versions contain breaking changes, there is a high probability that deploying RCs will break staging environments. Because of that, let's remove the deploy ability for release candidates for major updates.
This change does not apply to qa builds, which push to protonova environments.  Those can still be useful for creating an environment to explore the impacts of a major change on an isolated environment.

fix: do not auto-deploy major RCs

---

reporting/action.yml

The link to the protonova environment wasn't correctly putting the tag name because we weren't using backticks. This fixes that.

fix: fix interpolating proto name

---

deploy/lib/deployer/reporter.rb
deploy/spec/deployer/reporter_spec.rb
devbox.json
devbox.lock

Sometimes errors were giving errors that caused the reporting to crash because the backticks were not properly escaped when transitioning from ruby -> bash -> JavaScript.  This change uses the [format outlined here](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings) to ensure the format is correct.
In addition, I set up devbox to work correctly.
I tested this on [the test-js repo](https://github.com/planningcenter/test-js-auto-deploy-pkg/actions/runs/15287933725/job/43001886285)
---
- https://app.asana.com/0/0/1209797498874306

fix(deploy): escape reporting

---

deploy/action.yml
deploy/lib/deployer/repo/dependabot_proxy.rb

With the upgrade of dependabot recently, it created a scenario where calling corepack actions (which are now standard in the newer versions of dependabot) were looking in the incorrect place, since corepack will look at parent directories if the current one does not satisfy.
This issue was causing the package.json in the root of *this* repo to update to set the package manager to the one used in one of the repos we were copying.
To fix the solution, we are ensuring that we are cloning the dependency files into temporary directories.
I tested this locally as well as in [the testing repo](https://github.com/planningcenter/test-js-auto-deploy-pkg/actions/runs/15886890798).  In the testing, I found that there were some conflicts with using node 18, so I upgraded to 20.
---
- To see the …

fix(deploy): ensure package manager check doesn't leak

---

devbox.json
devbox.lock

Locally, running `bundle` for the `deploy` folder was failing to install `psych` correctly.  This updates devbox to make sure that it can run smoothly.
If you want to test it out, you can go to the deploy folder and then run `bundle` and `bundle exec rspec` to see it working.

chore: add devbox config

---

deploy/lib/deployer/repo.rb
deploy/lib/deployer/repo/base_updater.rb
deploy/lib/deployer/repo/dependabot_pull_request_updater.rb
deploy/lib/deployer/repo/pull_request_updater.rb
deploy/lib/deployer/reporter.rb
deploy/lib/deployer/repos.rb
deploy/spec/deployer/repo_spec.rb
deploy/spec/deployer/reporter_spec.rb
deploy/spec/deployer/repos_spec.rb
reporting/action.yml

Some of the messaging regarding updating particular packages have been less than clear.  For instance, when a repo is behind by a major version, the report would say that it updated and even create a link to a PR that doesn't exist.
With the introduction to "urgent" PRs and the ability to opt out of non-urgent PRs, it became clear that we would want to communicate clearly about these updates and that they are skipped.
In order to make this a possibility, we had to shift the status of repo updates from a binary (pass/fail), to a keyword status, with skipped being added.  Some of the logic was reworked to ensure that certain types of skips were handled correctly.  The breakdown looks like this:
| Reason | Is it reported? |
| -- | -- |
| excluded by `only` or `excluded` settings | ❌   |
| …

feat(Deploy): Improve messaging for skipped updates
